import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={geistSans.className} suppressHydrationWarning>
      <body className="bg-background text-foreground">
        <main className="min-h-screen flex flex-col items-center">
          <div className="flex-1 w-full flex flex-col gap-20 items-center">
            <nav className="w-full flex justify-center border-b border-b-foreground/10 h-16">
              <div className="w-full max-w-5xl flex justify-between items-center p-3 px-5 text-sm">
                <div className="flex gap-5 items-center font-semibold">
                  <Link href={'/'} className="text-2xl font-bold"><span className="text-pink-700">AI</span>Social Media</Link>
                </div>
              </div>
            </nav>
            
            <div className="flex flex-col gap-20 max-w-5xl p-5">
              {children}
            </div>

            <footer className="w-full flex items-center justify-center border-t mx-auto text-center text-xs gap-8 py-16">
              <p className="text-gray-400">
                Copyright © all rights reserved 2025
              <br />
              <br />
               Developers <span className="text-pink-700">Emanuel C. A Cardoso</span>; <span className="text-pink-700">Emilly Vieira</span>; <span className="text-pink-700">Henrique Szabo</span>; <span className="text-pink-700">Rafael Rapoulas</span>
              </p>
            </footer>
          </div>
        </main>
      </body>
    </html>
  );
}
